name: deploy to lambda

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.GH_PUSH_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GH_PUSH_AWS_SECRET_ACCESS_KEY }}
      - name: deploy
        run: |
          zip -j deploy.zip index.js
          aws lambda update-function-code --function-name=shorten_url --zip-file=fileb://deploy.zip
